---
name: bluefin-ondra
description: bluefin-dx for me

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://www.scootersoftware.com/scootersoftware.repo
    optfix:
      - brave.com
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware
    install:
      - keepassxc
      - brave-browser
      - bcompare

  - type: signing
